### ISSUE TITLE
 （MoeClub

### ISSUE THREAD

**Issue by 110560** [Aniverse/TrCtrlProToc0l#4]
MoeClub 应该失效了吧。
我  (16) 安装 LotServer  无法正常引导系统。..。
因为以前用的 4和一脚本 里面引用的 MoeClub 蛮好用的。..

**Comment by Aniverse** [comment]
感谢反馈，已修复。

原版的 MoeClub 脚本是只装 linux-image，我稍微改了下，加了个 headers，结果后边的删除其他内核的部分因为匹配的问题，把 headers 的依赖给删掉了……
这个问题应该以前也存在，只是因为我自己都用这个选项所以一直没发现
