### ISSUE TITLE
Ubuntu 20.04 环境安装启动魔改BBR出现错误 安装 libssl1.0.0 失败！

### ISSUE THREAD

**Issue by dycuo** [Aniverse/TrCtrlProToc0l#5]
以下是log的错误信息

  需要安装相关依赖以编译魔改 bbr / bbrplus，先更新系统源 ... Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Fetched 317 kB in 1s (406 kB/s)
Reading package lists...

  修复可能存在的依赖问题 ... Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  amd64-microcode intel-microcode iucode-tool libdbus-glib-1-2
  linux-modules-4.15.0-99-generic thermald
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 59 not upgraded.

Reading package lists...
Building dependency tree...
Reading state information...
Package multiarch-support is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'multiarch-support' has no installation candidate

  安装 libelf-dev ... Reading package lists...
Building dependency tree...
Reading state information...
libelf1 is already the newest version (0.176-1.1build1).
The following packages were automatically installed and are no longer required:
  amd64-microcode intel-microcode iucode-tool libdbus-glib-1-2
  linux-modules-4.15.0-99-generic thermald
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libc-dev-bin libc6-dev libcrypt-dev linux-libc-dev manpages manpages-dev
  zlib1g-dev
Suggested packages:
  glibc-doc man-browser
The following NEW packages will be installed:
  libc-dev-bin libc6-dev libcrypt-dev libelf-dev linux-libc-dev manpages
  manpages-dev zlib1g-dev
0 upgraded, 8 newly installed, 0 to remove and 59 not upgraded.
Need to get 7,598 kB of archives.
After this operation, 32.8 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/main amd64 manpages all 5.05-1 [1,314 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libc-dev-bin amd64 2.31-0ubuntu9 [71.8 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-42.46 [1,109 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libcrypt-dev amd64 1:4.4.10-10ubuntu4 [104 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libc6-dev amd64 2.31-0ubuntu9 [2,520 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu focal/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu1 [156 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu focal/main amd64 libelf-dev amd64 0.176-1.1build1 [57.0 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal/main amd64 manpages-dev all 5.05-1 [2,266 kB]
Fetched 7,598 kB in 1s (8,879 kB/s)
Selecting previously unselected package manpages.
(Reading database ... 46844 files and directories currently installed.)
Preparing to unpack .../0-manpages_5.05-1_all.deb ...
Unpacking manpages (5.05-1) ...
Selecting previously unselected package libc-dev-bin.
Preparing to unpack .../1-libc-dev-bin_2.31-0ubuntu9_amd64.deb ...
Unpacking libc-dev-bin (2.31-0ubuntu9) ...
Selecting previously unselected package linux-libc-dev:amd64.
Preparing to unpack .../2-linux-libc-dev_5.4.0-42.46_amd64.deb ...
Unpacking linux-libc-dev:amd64 (5.4.0-42.46) ...
Selecting previously unselected package libcrypt-dev:amd64.
Preparing to unpack .../3-libcrypt-dev_1%3a4.4.10-10ubuntu4_amd64.deb ...
Unpacking libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
Selecting previously unselected package libc6-dev:amd64.
Preparing to unpack .../4-libc6-dev_2.31-0ubuntu9_amd64.deb ...
Unpacking libc6-dev:amd64 (2.31-0ubuntu9) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../5-zlib1g-dev_1%3a1.2.11.dfsg-2ubuntu1_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1) ...
Selecting previously unselected package libelf-dev:amd64.
Preparing to unpack .../6-libelf-dev_0.176-1.1build1_amd64.deb ...
Unpacking libelf-dev:amd64 (0.176-1.1build1) ...
Selecting previously unselected package manpages-dev.
Preparing to unpack .../7-manpages-dev_5.05-1_all.deb ...
Unpacking manpages-dev (5.05-1) ...
Setting up manpages (5.05-1) ...
Setting up linux-libc-dev:amd64 (5.4.0-42.46) ...
Setting up libcrypt-dev:amd64 (1:4.4.10-10ubuntu4) ...
Setting up libc-dev-bin (2.31-0ubuntu9) ...
Setting up manpages-dev (5.05-1) ...
Setting up libc6-dev:amd64 (2.31-0ubuntu9) ...
Setting up zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1) ...
Setting up libelf-dev:amd64 (0.176-1.1build1) ...

  安装 libssl1.0.0 ... Reading package lists...
Building dependency tree...
Reading state information...
Package libssl1.0.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.0.0' has no installation candidate

$  错误 安装 libssl1.0.0 失败！

**Comment by Aniverse** [comment]
这是个已知 bug……最近比较懒没管它，迟点再修

**Comment by Aniverse** [comment]
这个是修好了，不过用自带的 5.4 内核还是装不上，先用 4.19.102 内核装吧（脚本里加入了这个选项，即先装这个内核，卸载掉其他内核，重启，再装魔改 bbr——要跑三次脚本）

**Comment by dycuo** [comment]
没错误了，感谢修正这个BUG，继续测试一下

**Comment by Aniverse** [comment]
我刚试了下，Ubuntu 18.04/20.04 用默认的 4.15.0-XXX / 5.4.0-XXX 内核也能成功编译了，估计是之前 headers 的安装上出现了偏差……现在是没问题了
